### ISSUE TITLE
compound_parameter_present() does not report the expected type

### ISSUE THREAD

**Issue by ktdreyer** [ktdreyer/koji-ansible#155]
When a user specifies the wrong type and we catch that in `compound_parameter_present()`, we raise a `ValueError` with a human-readable message about the parameter, the type we expected to find, and the that we found.

When we raise the `ValueError`, the message about the type we expected to find is not correct.

I uncovered this because I accidentally passed a bare string into the `inheritance` parameter for `koji_tag`. We expect a "list" here, rather than a "str". Here is the error message I got:

```
ValueError: inheritance must be a type, not a str
```

Here is the error message I expected:
```
ValueError: inheritance must be a list, not a str
```

This diff works:
```patch
--- a/library/koji_tag.py
+++ b/library/koji_tag.py
@@ -431,7 +435,7 @@ def compound_parameter_present(param_name, param, expected_type):
     if param not in (None, ''):
         if not isinstance(param, expected_type):
             raise ValueError(param_name + ' must be a '
-                             + expected_type.__class__.__name__
+                             + expected_type.__name__
                              + ', not a ' + param.__class__.__name__)
         return True
     return False
```

We need to add a unit test for this method, because the unit tests do not cover it currently.

**Comment by andrewschoen** [comment]
It looks like ``compound_parameter_present`` is mainly used for input validation. Could we instead set the ``type`` property on the arguments to the value we want? Ansible supports ``dict`` and ``list`` , which are the data types I see being validated by ``compound_parameter_present``. Is there another reason for this method that I'm not seeing?

https://docs.ansible.com/ansible/latest/dev_guide/developing_program_flow_modules.html#type

**Comment by ktdreyer** [comment]
Sure, I think that makes sense.

I think you're saying that we should drop the use of the "raw" type, like this?

```diff
diff --git a/library/koji_tag.py b/library/koji_tag.py
index 5481dc3..cdc562f 100644
--- a/library/koji_tag.py
+++ b/library/koji_tag.py
@@ -572,9 +572,9 @@ def run_module():
         koji=dict(),
         name=dict(required=True),
         state=dict(choices=['present', 'absent'], default='present'),
-        inheritance=dict(type='raw'),
-        external_repos=dict(type='raw'),
-        packages=dict(type='raw'),
+        inheritance=dict(type='list'),
+        external_repos=dict(type='list'),
+        packages=dict(type='dict'),
         groups=dict(type='raw'),
         arches=dict(),
         perm=dict(),
```

**Comment by andrewschoen** [comment]
Yeah, that's what I'm think we should do. Then we'd be able to rely on ansible's type checking and remove ``compound_parameter_present`` entirely. I can start on that work.

**Comment by ktdreyer** [comment]
Looks like we added "`raw`" in this commit here: ba6a95862f7cd7daa93610e4c1a81094cb78548c . It says there that it ended up transforming values in a way we didn't expect. hmm

**Comment by andrewschoen** [comment]
> Looks like we added "`raw`" in this commit here: [ba6a958](https://github.com/ktdreyer/koji-ansible/commit/ba6a95862f7cd7daa93610e4c1a81094cb78548c) . It says there that it ended up transforming values in a way we didn't expect. hmm

I'm not fully understanding what ``An empty value is coreced into a non-empty list: ['']`` means in that commit message. Do we know what kind of input produced the issue?

**Comment by ktdreyer** [comment]
I looked at this some more, and here is what I *think* this means:

Prior to that ba6a95862f7cd7daa93610e4c1a81094cb78548c commit, if a user did not specify any `inheritance:` parameter to the `koji_tag` module, then we would effectively treat it as an empty list, *and* we would always delete all existing tag inheritance relationships on a tag.

This is a surprising user experience (deleting things unexpectedly when the user did not specify anything) and it makes it harder to adopt koji-ansible for a tag configuration that's already set up. @ahills changed that so that koji-ansible will only delete existing inheritance relationships `if compound_parameter_present('inheritance', inheritance, list):`.

I think this means that we are safe to drop `raw` in the argspec, but we do need to keep the conditionals and simplify them, like:

```diff
diff --git a/library/koji_tag.py b/library/koji_tag.py
index 5481dc3..0229aa9 100644
--- a/library/koji_tag.py
+++ b/library/koji_tag.py
@@ -517,7 +517,7 @@ def ensure_tag(session, name, check_mode, inheritance, external_repos,
                 session.editTag2(name, **edits)
 
     # Ensure inheritance rules are all set.
-    if compound_parameter_present('inheritance', inheritance, list):
+    if inheritance:
         inheritance_result = ensure_inheritance(session, name, taginfo['id'],
                                                 check_mode, inheritance)
         if inheritance_result['changed']:
```

**Comment by andrewschoen** [comment]
Yup, I think you're right here. If we keep the default as ``None`` and then always check it's value before using it then we're ok to remove ``raw`` and use the appropriate type.

**Comment by ktdreyer** [comment]
cool!
