### ISSUE TITLE
Architecture for a buildroot tag should be compared as a set

### ISSUE THREAD

**Issue by pbabinca** [ktdreyer/koji-ansible#27]
Order of architectures in a buildroot tag doesn't matter. These two are equivalent from Koji point of view:

- x86_64 ppc64le
- ppc64le x86_64

E.g.:
```
TASK [rhceph3 : 3.1 build tag] ***************************************************************************************************************************************************************
changed: [rcm-compose-nightly-02] => {"changed": true, "stdout_lines": ["ceph-3.1-rhel-7-build: changed arches from \"ppc64le x86_64\" to \"x86_64 ppc64le\""]}
```

**Comment by ktdreyer** [comment]
I think we should just break the existing syntax and make this a real list. Even if the Koji API uses a string here, it would be a lot more user-friendly to use a list, like `koji_host` does.

@ahills are you ok with that backwards-incompatible change?

**Comment by ktdreyer** [comment]
PR https://github.com/ktdreyer/koji-ansible/pull/31 changes `koji_tag` to require a real list for `arches`.

**Comment by mizdebsk** [comment]
Order of architectures does matter in a few subtle cases, for example SRPM that is included in the build is the one built on the first arch on the list. Likewise, rpmdiff compares RPMs built on the first arch with RPMs built on other arches.

**Comment by ktdreyer** [comment]
@mizdebsk thank you very much for pointing this out. We should document Koji's behavior in `koji-ansible` so it's clear to administrators.

It sounds like we could still use a `list` type for `arches` in the `koji_tag` module, but we should not make it a `set` comparison, and we should explicitly enforce ordering.

**Comment by ktdreyer** [comment]
After thinking about this more, I'm actually leaning towards not implementing this now. There are so many places where we would have to translate back and forth between the strings and a list.

When Koji changes its own hub API to use a list, it will be easier.

**Comment by ktdreyer** [comment]
@mizdebsk @pbabinca I've updated the documentation for this instead: https://github.com/ktdreyer/koji-ansible/pull/53 . Please take a look.

**Comment by ktdreyer** [comment]
It turns out that ordering does matter, so I'm going to close this one.
