### ISSUE TITLE
Considering making koji-ansible an ansible collection

### ISSUE THREAD

**Issue by cverna** [ktdreyer/koji-ansible#48]
I am working on a collection for bodhi (https://github.com/cverna/bodhi-ansible) and i would like to have a dependency to koji-ansible.

Are you considering creating an ansible collection for koji-ansible ?

**Comment by ktdreyer** [comment]
Thanks for asking. I am considering it, yep. Long-term, I think it would be a good idea to do this.

A while ago I wrote a change to the README about this (https://github.com/ktdreyer/koji-ansible/pull/45). Since that time, the Ansible product managers have [given their support](https://www.ansible.com/resources/webinars-training/collections-future-of-how-ansible-content-is-handled) to the Collections concept, which is a great sign.

It looks like a lot of the pieces are still under heavy development in Ansible 2.9, so I will continue to keep an eye on this.

**Comment by ktdreyer** [comment]
I played around with today.

I want to avoid a lot of release engineering busywork upfront (like a bumping number in `galaxy.yml` by hand, etc). I will set up a CI pipeline to publish every master commit to the Galaxy Hub as a "prerelease". That will decouple the work of "make koji-ansible a collection on the Galaxy Hub" from the work of "publish stable releases and use semver".

**Comment by ktdreyer** [comment]
I have a work-in-progress branch (`ansible-collection`) that uses GitHub Actions to push every master branch commit to [the Galaxy repo](https://galaxy.ansible.com/ktdreyer/koji_ansible). I've discovered a few things along the way:

- There is no way to delete any content from Galaxy. I cannot delete the collection or any versions. Oops
- There is no easy way to add the Git build metadata as specified in semver.org. This makes it hard for users to easily install the latest version from Galaxy, or to know what Git snapshot they are running. I've commented in [upstream ansible issue #64905](https://github.com/ansible/ansible/issues/64905) about this problem.

**Comment by ktdreyer** [comment]
There are certainly some UX problems here, but at this point, I think we should still push all commits to Ansible Galaxy going forward. We can sort out the above problems with the upstream Ansible Galaxy project separately.

https://github.com/ktdreyer/koji-ansible/pull/100 enables automatic publishing for the master branch.

**Comment by ktdreyer** [comment]
The latest problem is that I uploaded a version "0.0.159+git.7318f7b5" to Ansible Galaxy four months ago when I was playing around with this, and now Galaxy treats all my other Git snapshots as "older", even though they are technically newer and better.

After talking with @ignatenkobrain about the version numbering, I think we should just use version numbers that Ansible Galaxy will sort in the way I intend. I need to go back and experiment to make sure that clients will work with that versioning scheme.

**Comment by ktdreyer** [comment]
I've filed https://github.com/ktdreyer/koji-ansible/issues/168 to track the versioning problem, and I plan to fix that this week.

**Comment by ktdreyer** [comment]
We've merged the versioning fix, and https://galaxy.ansible.com/ktdreyer/koji_ansible looks right now.
