### ISSUE TITLE
generate-playbook does not play well with virtualenv's

### ISSUE THREAD

**Issue by yazug** [ktdreyer/koji-ansible#93]
generate-playbook has hardcoded #!/usr/bin/python3 which does not play well with virtualenv

probably should have #!/usr/bin/env python3 instead

**Comment by ktdreyer** [comment]
I've switched the shebang in https://github.com/ktdreyer/koji-ansible/pull/94

**Comment by ktdreyer** [comment]
This is fixed in master now.
